spring.datasource.url: jdbc:h2:file:./camunda-h2-database

server:
  port: 7070

camunda.bpm.admin-user:
  id: demo
  password: demo

spring:
  output:
    ansi:
      enabled: ALWAYS
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
